#!/usr/bin/env python3
from __future__ import annotations

import shutil
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DIST = ROOT / "dist"
SKILL_ROOT = ROOT / "think-tank"
MARKETPLACE = ROOT / "marketplace"


def reset_dir(path: Path) -> None:
    if path.exists():
        shutil.rmtree(path)
    path.mkdir(parents=True, exist_ok=True)


def copy_skill_bundle(target_root: Path) -> None:
    target = target_root / "think-tank"
    shutil.copytree(SKILL_ROOT, target)
    for path in target.rglob("*"):
        if path.name == ".DS_Store":
            path.unlink()


def zip_dir(source_dir: Path) -> None:
    archive_base = str(source_dir)
    shutil.make_archive(archive_base, "zip", root_dir=source_dir.parent, base_dir=source_dir.name)


def write_dist_readme() -> None:
    content = """# Distribution Artifacts

This directory is generated by:

```bash
python3 scripts/package_agent_distributions.py
```

Artifacts:

- `openai-chatgpt-skill/think-tank/`
  OpenAI Skills / Codex-compatible Agent Skills bundle.
- `claude-code-skill/think-tank/`
  Claude Code skill bundle for installation into `~/.claude/skills/think-tank/`.

Zip archives are generated next to each folder for manual upload or distribution.
"""
    (DIST / "README.md").write_text(content, encoding="utf-8")


def main() -> None:
    reset_dir(DIST)

    openai_dir = DIST / "openai-chatgpt-skill"
    claude_skill_dir = DIST / "claude-code-skill"
    openai_dir.mkdir(parents=True, exist_ok=True)
    claude_skill_dir.mkdir(parents=True, exist_ok=True)

    copy_skill_bundle(openai_dir)
    copy_skill_bundle(claude_skill_dir)

    shutil.copy2(MARKETPLACE / "openai-skill-listing.yaml", openai_dir / "listing.yaml")
    shutil.copy2(MARKETPLACE / "claude-skill-listing.yaml", claude_skill_dir / "listing.yaml")

    write_dist_readme()

    zip_dir(openai_dir)
    zip_dir(claude_skill_dir)

    print("Built distribution artifacts:")
    print(f"- {openai_dir}")
    print(f"- {claude_skill_dir}")


if __name__ == "__main__":
    main()
